In [2]:
import cv2
import numpy as np
import requests
import datetime

In [3]:
from keras.models import load_model
model = load_model('ferdetect.h5')

In [4]:
emotion_dict = {0: "Angry", 1: "Disgusted", 2: "Fearful", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprise"}
negative=["Angry","Disgusted","Fearful","Sad"]

In [7]:
cap = cv2.VideoCapture(0)
url = 'http://13.232.44.96:8080/rest/users/save'

while True:
    # Find haar cascade to draw bounding box around face
    ret, frame = cap.read()
    if not ret:
        break
    facecasc = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = facecasc.detectMultiScale(gray,scaleFactor=1.3, minNeighbors=5)

    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y-50), (x+w, y+h+10), (255, 0, 0), 2)
        roi_gray = gray[y:y + h, x:x + w]
        cropped_img = np.expand_dims(np.expand_dims(cv2.resize(roi_gray, (48, 48)), -1), 0)
        prediction = model.predict(cropped_img)
        print(prediction)
        maxindex = int(np.argmax(prediction))
        cv2.putText(frame, emotion_dict[maxindex], (x+20, y-60), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        if emotion_dict[maxindex] in negative:
            cv2.putText(frame, "Negative Emotion", (40,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        
        if emotion_dict[maxindex] in negative:
            now = datetime.datetime.now()
            current_time = now.strftime("%H:%M:%S") 
            today = str(datetime.date.today())
            data = {
                "id":5,
                "name": "KEERTHAN",
                "time_stamp": current_time,
                "date":today,
                "alert_type": "DISTRESS DETECTED"
          }
             
        #if (previous!= current):
        #print (current)
            requests.post(url,json = data)
            
        #previous = current
        
    #cv2.imshow('Video', cv2.resize(frame,(960,540),interpolation = cv2.INTER_CUBIC))
    cv2.imshow('Video',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[[0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00 7.652944e-17
  0.000000e+00 0.000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 7.092633e-38
  0.000000e+00 1.000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.000000e+00 0.000000e+00 9.208958e-30 1.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00
  3.5375094e-17 0.0000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.         0.         0.43479687 0.         0.56520313 0.
  0.        ]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0.]]
[[2.5

[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 5.8556943e-29
  0.0000000e+00 0.0000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0.000000e+00 0.000000e+00 0.000000e+00 5.659558e-21 1.000000e+00
  0.000000e+00 0.000000e+00]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0.]]

In [4]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 46, 46, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 44, 44, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 22, 22, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 22, 22, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 20, 128)       73856     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 8, 8, 128)         1